project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_API_TOKEN
base_url_env: CROWDIN_BASE_URL
base_path: "."

preserve_hierarchy: true

files:
  [
    {
      "source": "/packages/breadcrumbs/locales/en/messages.po",
      "dest": "elements/packages/breadcrumbs/messages.po",
      "translation": "/packages/breadcrumbs/locales/%two_letters_code%/messages.po",
    },
    {
      "source": "/packages/button/locales/en/messages.po",
      "dest": "elements/packages/button/messages.po",
      "translation": "/packages/button/locales/%two_letters_code%/messages.po",
    },
    {
      "source": "/packages/select/locales/en/messages.po",
      "dest": "elements/packages/select/messages.po",
      "translation": "/packages/select/locales/%two_letters_code%/messages.po",
    },
    {
      "source": "/packages/attention/locales/en/messages.po",
      "dest": "elements/packages/attention/messages.po",
      "translation": "/packages/attention/locales/%two_letters_code%/messages.po",
    },
    {
      "source": "/packages/toast/locales/en/messages.po",
      "dest": "elements/packages/toast/messages.po",
      "translation": "/packages/toast/locales/%two_letters_code%/messages.po",
    },
    {
      "source": "/packages/pill/locales/en/messages.po",
      "dest": "elements/packages/pill/messages.po",
      "translation": "/packages/pill/locales/%two_letters_code%/messages.po",
    },
  ]
