patchedDependencies:
  '@vitest/pretty-format': patches/@vitest__pretty-format.patch
  custom-element-vs-code-integration: patches/custom-element-vs-code-integration.patch
  vitest-browser-lit: patches/vitest-browser-lit.patch
