packages:
  - packages/*

ignoredBuiltDependencies:
  - esbuild

patchedDependencies:
  '@vitest/pretty-format': patches/@vitest__pretty-format.patch
  custom-element-vs-code-integration: patches/custom-element-vs-code-integration.patch
