name: Lint

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          cache: "pnpm"
          node-version: 24.16.0
      - run: pnpm i

      - name: Lint
        run: pnpm lint
    
      - name: Build
        run: pnpm build

      - name: Publint
        run: pnpm lint:package

      # test after build so we have compiled Lingui files to import
      - name: Install Playwright
        run: pnpm exec playwright install --with-deps
      - name: Test
        run: pnpm test && pnpm test:module-resolution && pnpm test:output-validation
